sudo: required
services:
    - docker

before_install:
    - docker build -t manussanun/docker-react -f Dockerfile.dev .

script:
    - docker run manussanun/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    butcket_name: "elasticbeanstalk-us-east-1-775774840812"
    bucket_path: "docker-react"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY